version: '3.8'

services:
  backend:
    build: .
    container_name: userservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user
      - MYSQL_HOST=mysql
      - CONSUL_HOST=consul

    depends_on:
      - rabbitmq
      - mysql
      - consul

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=user

  consul:
    image: bitnami/consul:latest
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
    volumes:
      - 'consul-persistence:/bitnami'



volumes:
  db:
    driver: local
  consul-persistence:
    driver: local