###
PUT http://localhost:8080/1L
Content-Type: application/json

{
"userName":"test",
"firstName":"madicken",
"lastName":"larsson"
}
###
POST http://localhost:8080/register
Content-Type: application/json
{
"username": "anna.andersson@gmail.com",
"password": "test"
}